baseURL = "https://zjpsycholin.github.io/psycholinguistics/"
languageCode = "en-us"
title = "Introduction to Psycholinguistics"
theme = "archie"
copyright = "© Zhang Jun"




[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[params]
  mode = "auto"
  useCDN = false
  subtitle = ""
  katex = true

[menu]
  [[menu.main]]
    name = "Welcome"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Syllabus"
    url = "/syllabus/"
    weight = 2

  [[menu.main]]
    name = "Week-01"
    url = "/week01/"
    weight = 3

  [[menu.main]]
    name = "Week-02"
    url = "/week02/"
    weight = 4

  [[menu.main]]
    name = "Week-03"
    url = "/week03/"
    weight = 5

  [[menu.main]]
    name = "Week-04"
    url = "/week04/"
    weight = 6

  [[menu.main]]
    name = "Week-05"
    url = "/week05/"
    weight = 7

  [[menu.main]]
    name = "Week-06"
    url = "/week06/"
    weight = 8

  [[menu.main]]
    name = "Week-07"
    url = "/week07/"
    weight = 9

  [[menu.main]]
    name = "Week-08"
    url = "/week08/"
    weight = 10

  [[menu.main]]
    name = "Week-09"
    url = "/week09/"
    weight = 11

  [[menu.main]]
    name = "Week-10"
    url = "/week10/"
    weight = 12

  [[menu.main]]
    name = "Week-11"
    url = "/week11/"
    weight = 13

  [[menu.main]]
    name = "Week-12"
    url = "/week12/"
    weight = 14

  [[menu.main]]
    name = "Week-13"
    url = "/week13/"
    weight = 15

  [[menu.main]]
    name = "Week-14"
    url = "/week14/"
    weight = 16

  [[menu.main]]
    name = "Week-15"
    url = "/week15/"
    weight = 17

  [[menu.main]]
    name = "Week-16"
    url = "/week16/"
    weight = 18

  [[menu.main]]
    name = "Week-17"
    url = "/week17/"
    weight = 19

  
